apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth-depl
  labels:
    app: api-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
        - name: api-auth
          # eval $(minikube docker-env)
          # cd to service && docker build -t penkong/vanillanodemongo .
          image: 'penkong/vanillanodepg:latest'
          # imagePullPolicy: Never // if use local image
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: confmap
                  key: port

            - name: DBURL
              valueFrom:
                configMapKeyRef:
                  name: confmap
                  key: dburl

            - name: DBNAME
              valueFrom:
                configMapKeyRef:
                  name: confmap
                  key: dbname

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: confmap
                  key: envnode

            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: pgpass

            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: pguser

            - name: CORS
              valueFrom:
                configMapKeyRef:
                  name: confmap
                  key: cors

            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwtkey

            - name: JWT_TTL
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: jwtttl

          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
          ports:
            - containerPort: 5003

---
apiVersion: v1
kind: Service
metadata:
  name: api-auth-srv
spec:
  selector:
    app: api-auth
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
