apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
# echo -n 'root' | base64
data:
  pguser: cm9vdA==
  pgpass: c2VjcmV0
  pgadminpass: c2VjcmV0
  jwtttl: MzY1ZA==
  jwtkey: and0a2V5
# k apply -f name

# --- FOR WHEN WANT USE TLS
# apiVersion: v1
# kind: Secret
# metadata:
#   name: myapp-sec-tls
#   namespace: default
# data:
#   tsl.crt: bas64 encoded
#   tsl.key: bas64 encoded
# type: kubernetes.io/tls
