version: '3.4'
services:

  #
  pg:
    image: 'postgres:13.2-alpine'
    stdin_open: true
    restart: always
    volumes: 
      - pgvol:/var/lib/postgresql/data 
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - PGPORT=5432
    ports: 
      - 5432:5432

  #
  pgadmin:
    image: 'dpage/pgadmin4'
    stdin_open: true
    restart: always
    depends_on:
      - pg
    environment: 
      - PGADMIN_DEFAULT_EMAIL=nazemi.works@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports: 
      - 8005:80


  #
  api:
    build: 
      context: ../server
      dockerfile: Dockerfile.dev
    restart: always
    stdin_open: true
    depends_on:
      - pg
    volumes: 
      - /app/node_modules 
      - ../server:/app
    environment:
      - PORT=5002
      - DBURL=pg
      - DBNAME=devrefvanillanodesql
      - NODE_ENV=development
      - PGPASS=secret
      - PGUSER=root
      - CORS=http://localhost:3000
      - JWT_KEY=yhgewy5ehuyrhbe56y
      - JWT_TTL=365d
    ports: 
      - 5002:5002

volumes: 
  pgvol:
    driver: local